version: "3.8"
services:
  #base-component

  mysql8:
    hostname: mysql_8
    container_name: mysql_8
    image: mysql:8.0.32
    restart: always # 设置容器自启模式
    expose:
      - "3306"
    ports:
      - "5306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    #      - MYSQL_USER=admin
    #      - MYSQL_PASSWORD=welcome1
    volumes:
      - ./config/mysql8/init_script/:/docker-entrypoint-initdb.d/
      - ./config/mysql8/config/:/etc/mysql/mysql.conf.d/
    command: mysqld --default-time-zone=''+08:00''
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u porta --password=porta
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55

  rabbitmq:
    hostname: rabbitmq
    container_name: rabbitmq
    image: rabbitmq:3.11.10-management
    restart: always
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: 123456
      RABBITMQ_DEFAULT_VHOST: coupler

  redis:
    hostname: redis
    container_name: redis
    image: redis:7.0.8
    restart: always
    ports:
      - "6379:6379"

  minio:
    hostname: minio
    container_name: minio
    image: minio/minio:RELEASE.2021-06-17T00-10-46Z
    restart: always
    ports:
      - "9090:9000"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    volumes:
      - /Users/jade/Documents/javaSoftware/dockerdata/minio/data:/data
      - /Users/jade/Documents/javaSoftware/dockerdata/minio/config:/etc/minio
    command: server /data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3

#  nacos-server:
#    hostname: nacos-server
#    container_name: nacos-server
#    image: nacos/nacos-server:v2.2.2-slim
#    platform: linux/amd64
#    restart: always
#    env_file:
#      - ./config/nacos/custom-application-config.env
#    environment:
#      MODE: standalone
#      NACOS_APPLICATION_PORT: 8848
#      SPRING_DATASOURCE_PLATFORM: mysql
#      MYSQL_SERVICE_HOST: localhost
#      MYSQL_SERVICE_PORT: 5306
#      MYSQL_SERVICE_DB_NAME: nacos
#      MYSQL_SERVICE_USER: porta
#      MYSQL_SERVICE_PASSWORD: porta
#      MYSQL_SERVICE_DB_PARAM: characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useUnicode=true&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
#      JVM_XMS: 256m
#      JVM_XMX: 256m
#      JVM_XMN: 128m
#      JVM_MS: 128m
#      JVM_MMS: 128m
#    volumes:
#      - /Users/jade/Documents/javaSoftware/dockerdata/nacos/logs:/home/nacos/logs
#    ports:
#      - '8848:8848'
#      - '9848:9848'
#      - '9849:9849'
#    depends_on:
#      mysql8:
#        condition: service_healthy

volumes:
  data: null
  mysql: null
  rabbitmq: null
  component: null

