services:
  #base-component

  mysql8:
    hostname: mysql_8
    container_name: mysql_8
    image: mysql:8.0.32
    restart: always # 设置容器自启模式
    expose:
      - "3306"
    ports:
      - "5306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    #      - MYSQL_USER=admin
    #      - MYSQL_PASSWORD=welcome1
    volumes:
      - ./config/mysql8/init_script/:/docker-entrypoint-initdb.d/
      - ./config/mysql8/config/:/etc/mysql/mysql.conf.d/
    command: mysqld --default-time-zone=''+08:00''
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u porta --password=porta
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55

  rabbitmq:
    hostname: rabbitmq
    container_name: rabbitmq
    image: rabbitmq:3.11.10-management
    restart: always
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: welcome1
      RABBITMQ_DEFAULT_VHOST: vhost_jade

  redis:
    hostname: redis
    container_name: redis
    image: redis:7.0.8
    restart: always
    ports:
      - "6379:6379"

  minio:
    hostname: minio
    container_name: minio
    image: minio/minio:RELEASE.2023-02-27T18-10-45Z
    restart: always
    ports:
      - "9090:9000"
      - '9001:9001'
    environment:
      TZ: Asia/Shanghai
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
      MINIO_DEFAULT_BUCKETS: dev
    volumes:
      - /Users/jade/Documents/javaSoftware/dockerdata/minio/data:/data
      - /Users/jade/Documents/javaSoftware/dockerdata/minio/config:/etc/minio
    command: server --console-address ':9001' /mnt/data
    privileged: true
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3

  elasticsearch:
    image: elasticsearch:7.17.21
    container_name: elasticsearch
    restart: always
    environment:
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
      "discovery.type": "single-node"
      "xpack.security.enabled": false
    ports:
      - '9200:9200'
      - '9300:9300'
    volumes:
      - "/Users/jade/Documents/javaSoftware/dockerdata/elasticsearch/data:/usr/share/elasticsearch/data/"
      - "/Users/jade/Documents/javaSoftware/dockerdata/elasticsearch/logs:/usr/share/elasticsearch/logs/"
      - "./config/elasticsearch/plugins/:/usr/share/elasticsearch/plugins/"
    deploy:
      # Configures resource constraints.
      resources:
        #        limits:
        #          cpus: '1'
        #          memory: 2G
        reservations:
          # cpus: '0.25'
          memory: 512M

#  kibana:
#    image: kibana:7.17.21
#    container_name: kibana
#    restart: always
#    depends_on:
#      - elasticsearch
#    environment:
#      ELASTICSEARCH_URL: http://elasticsearch:9200
#    ports:
#      - '5601:5601'

  # nacos-server:
  #   image: nacos/nacos-server:v2.2.0-slim
  #   container_name: nacos-server
  #   restart: always
  #   environment:
  #     MODE: standalone
  #     NACOS_APPLICATION_PORT: 8848
  #     SPRING_DATASOURCE_PLATFORM: mysql
  #     MYSQL_SERVICE_HOST: 192.168.2.11
  #     MYSQL_SERVICE_PORT: 5306
  #     MYSQL_SERVICE_DB_NAME: nacos
  #     MYSQL_SERVICE_USER: porta
  #     MYSQL_SERVICE_PASSWORD: porta
  #     MYSQL_SERVICE_DB_PARAM: characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useSSL=false&serverTimezone=GMT%2B8
  #     JVM_XMS: 128m
  #     JVM_XMX: 128m
  #     JVM_XMN: 64m
  #   depends_on:
  #     - mysql8
  #   ports:
  #     - '8848:8848'
  #     - '9848:9848'
  #     - '9849:9849'

volumes:
  data:
  mysql: null
  rabbitmq: null
  component: null

