SET GLOBAL SQL_MODE = 'STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION';
SET @@session.time_zone = "+08:00";
CREATE USER 'porta'
  IDENTIFIED BY 'porta';

CREATE DATABASE dkl_test CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci;

GRANT ALL PRIVILEGES ON *.* TO 'porta';
commit;
