SET GLOBAL SQL_MODE = 'STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION';

CREATE USER 'porta' IDENTIFIED BY 'porta';
GRANT ALL PRIVILEGES ON *.* TO 'porta'@'%';

# CREATE DATABASE dkl_test CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
CREATE DATABASE portal_site CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;


commit;
