version: "3.8"
services:
  mongodb:
    image: mongodb/mongodb-community-server:5.0.23-ubi8
    container_name: mongodb
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGODB_INITDB_ROOT_USERNAME: porta
      MONGODB_INITDB_ROOT_PASSWORD: porta
    volumes:
      - "/data/docker/mongodb/data/configdb/:/data/configdb/"
      - "/data/docker/mongodb/data/db/:/data/db/"
      - "/data/docker/mongodb/data/logs/:/data/logs/"
    deploy:
      # Configures resource constraints.
      resources:
        limits:
          cpus: '2'
          memory: 4096M
        reservations:
          # cpus: '0.50'
          memory: 1024M
